# Generated by Django 3.0.4 on 2020-05-18 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='Modify date')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name': 'guestbook',
                'verbose_name_plural': 'guestbook',
                'db_table': 'guestbook',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestbook_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guestbook.GuestBook')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'like',
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(verbose_name='Contnet')),
                ('reference_comment_id', models.IntegerField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='Modify date')),
                ('guestbook_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guestbook.GuestBook')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
                'db_table': 'comment',
            },
        ),
    ]
